import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

// import { ColorModeContext, useMode } from '../theme'

import Topbar from '@/components/global/Topbar'
import LeftSidebar from '@/components/global/LeftSidebar'

// import { CssBaseline, ThemeProvider } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  // const [theme, colorMode] = useMode();

  return (

    <html lang="en">
      <body className={inter.className}>

        <Topbar />

        <LeftSidebar />

        <main className='bg-yellow-300 main-container'>
          <section>
            {children}
          </section>
        </main>

      </body>
    </html>
  )
}
